# Generated by Django 5.2.7 on 2025-10-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioBuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiotRSOToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=200, unique=True)),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(blank=True, max_length=1024)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('id_token', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
